# Generated by Django 6.0.1 on 2026-05-02 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0001_initial"),
        ("organize_test", "0011_alter_newtest_difficulty"),
    ]

    operations = [
        migrations.AddField(
            model_name="testattempt",
            name="score",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="testattempt",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selected_answer", models.TextField(blank=True, null=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessment.testattempt",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="organize_test.questionmodel",
                    ),
                ),
            ],
        ),
    ]
