# Generated by Django 6.0.1 on 2026-05-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0002_testattempt_score_alter_testattempt_status_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="testattempt",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
