# Generated by Django 6.0.1 on 2026-05-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0003_testattempt_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="testattempt",
            name="scheduled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
