# Generated by Django 6.0.1 on 2026-02-04 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organize_test", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_text",
                    models.TextField(help_text="Enter the question text"),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("mcq", "Multiple Choice"),
                            ("coding", "Coding"),
                            ("descriptive", "Descriptive"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        max_length=20,
                    ),
                ),
                ("marks", models.IntegerField()),
                (
                    "expected_solution",
                    models.TextField(
                        blank=True,
                        help_text="Sample solution for coding question",
                        null=True,
                    ),
                ),
                (
                    "sample_answer",
                    models.TextField(
                        blank=True,
                        help_text="Key points to be covered in answer",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="newtest",
            name="difficulty",
            field=models.CharField(
                choices=[("medium", "Medium"), ("hard", "Hard"), ("easy", "Easy")],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="QuestionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option_text", models.CharField(max_length=400)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="organize_test.question",
                    ),
                ),
            ],
        ),
    ]
