# Generated by Django 6.0.1 on 2026-03-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organize_test", "0003_alter_newtest_difficulty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newtest",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("hard", "Hard"), ("medium", "Medium")],
                max_length=20,
            ),
        ),
    ]
