# Generated by Django 6.0.1 on 2026-04-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organize_test", "0004_alter_newtest_difficulty"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("options", models.JSONField(blank=True, null=True)),
                ("answer", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
