# Generated by Django 6.0.1 on 2026-04-22 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organize_test", "0005_questionmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="test",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="organize_test.newtest",
            ),
        ),
        migrations.AddField(
            model_name="questionmodel",
            name="test",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="organize_test.newtest",
            ),
        ),
        migrations.AlterField(
            model_name="newtest",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                max_length=20,
            ),
        ),
    ]
