# Generated by Django 6.0.1 on 2026-04-22 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organize_test", "0006_question_test_questionmodel_test_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="test",
        ),
        migrations.RemoveField(
            model_name="questionmodel",
            name="test",
        ),
        migrations.AlterField(
            model_name="newtest",
            name="difficulty",
            field=models.CharField(
                choices=[("medium", "Medium"), ("hard", "Hard"), ("easy", "Easy")],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TestQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marks", models.IntegerField(default=2)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organize_test.questionmodel",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organize_test.newtest",
                    ),
                ),
            ],
            options={
                "unique_together": {("test", "question")},
            },
        ),
        migrations.AddField(
            model_name="newtest",
            name="questions",
            field=models.ManyToManyField(
                through="organize_test.TestQuestion", to="organize_test.questionmodel"
            ),
        ),
    ]
