# Generated by Django 6.0.1 on 2026-04-22 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "organize_test",
            "0007_remove_question_test_remove_questionmodel_test_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newtest",
            name="questions",
        ),
        migrations.AddField(
            model_name="questionmodel",
            name="is_selected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="questionmodel",
            name="marks",
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name="questionmodel",
            name="test",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="organize_test.newtest",
            ),
        ),
        migrations.AlterField(
            model_name="newtest",
            name="difficulty",
            field=models.CharField(
                choices=[("medium", "Medium"), ("easy", "Easy"), ("hard", "Hard")],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="TestQuestion",
        ),
    ]
