# Generated by Django 6.0.1 on 2026-04-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "organize_test",
            "0008_remove_newtest_questions_questionmodel_is_selected_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="newtest",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("hard", "Hard"), ("medium", "Medium")],
                max_length=20,
            ),
        ),
    ]
