# Generated by Django 6.0.1 on 2026-04-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organize_test", "0009_alter_newtest_difficulty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newtest",
            name="difficulty",
            field=models.CharField(
                choices=[("hard", "Hard"), ("medium", "Medium"), ("easy", "Easy")],
                max_length=20,
            ),
        ),
    ]
