# Generated by Django 6.0.1 on 2026-05-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organize_test", "0010_alter_newtest_difficulty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newtest",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                max_length=20,
            ),
        ),
    ]
