# Generated by Django 6.0.1 on 2026-06-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organize_test", "0011_alter_newtest_difficulty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newtest",
            name="difficulty",
            field=models.CharField(
                choices=[("medium", "Medium"), ("easy", "Easy"), ("hard", "Hard")],
                max_length=20,
            ),
        ),
    ]
