# Generated by Django 6.0.1 on 2026-01-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("score", models.IntegerField()),
                ("skills", models.JSONField(default=list)),
                ("status", models.BooleanField(default=False)),
            ],
        ),
    ]
