# Generated by Django 6.0.1 on 2026-01-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_screening", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="resume",
            field=models.FileField(default=0, upload_to="resumes/"),
            preserve_default=False,
        ),
    ]
