# Generated by Django 6.0.1 on 2026-03-25 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_parser", "0001_initial"),
        ("resume_screening", "0002_userinfo_resume"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="job_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="resume_parser.jobrole",
            ),
        ),
    ]
