# Generated by Django 6.0.1 on 2026-04-29 17:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organize_test", "0009_alter_newtest_difficulty"),
        ("resume_screening", "0003_userinfo_job_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("token", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("status", models.CharField(default="not_started", max_length=20)),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organize_test.newtest",
                    ),
                ),
            ],
        ),
    ]
