# Generated by Django 6.0.1 on 2026-04-30 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume_screening", "0004_testattempt"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TestAttempt",
        ),
    ]
